apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ag6bt54o9-nodejs
  janus-idp.io/tekton: ag6bt54o9-nodejs
  backstage.io/kubernetes-id: ag6bt54o9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ag6bt54o9-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
