apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ag6bt54o9-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:40fccd249119a0cc8ee1a47266b200f2f4df39c0@sha256:02df6e257f0b33553265c339fbc7d673ae9f77c79ad6fcd7c596d9dbf1e32cfc
          name: container-image
